### ISSUE TITLE
People add-on: add view link to people list overview screen

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/eea-people-addon#11]
Original Codebase ticket: https://events.codebasehq.com/projects/event-espresso/tickets/11085

**Summary**
If you hover over an event name from the events overview screen, then there is an option to view it on the front end: https://cl.ly/0A3D2L1n0415
We also have a view link for venues on the venues overview screen: https://cl.ly/2J01021C2t06

Could we also add something similar for the people overview screen?

https://cl.ly/2H1F3o1P0G30

**Comment by nerrad** [comment]
Still plan on doing eventually.
