### ISSUE TITLE
Improved Generic Styling of People on Events

### ISSUE THREAD

**Issue by mnelson4** [eventespresso/eea-people-addon#14]
## Issue Overview
I created a plugin [eea-people-image-styling.zip](https://github.com/eventespresso/eea-people-addon/files/1996014/eea-people-image-styling.zip) (as part of ICE time) that adds some styling to the people list that improved it for a site I run (wpcowichan.org).
Here's what an event with some people on my site looks like using the twenty seventeen theme, and the people add-on:
![people original](https://user-images.githubusercontent.com/1766382/39934357-623fb5b0-54fa-11e8-8ad2-5bc608f0a6ff.png)

Whereas when I activate the plugin, it becomes this: 
![people with extra styling](https://user-images.githubusercontent.com/1766382/39934377-6cc25222-54fa-11e8-8bd6-6563b3cb8ad8.png)

Which IMO looks better (although the rectagulalar images look pretty bad. that's another issue though). The main trouble with this is that these styling improvements only work if all people have an image. If they don't, the default styling would probably be better.

So it might be better if we have an option in the admin, called something like "People on Event Display Style" with options "List of names" (which would use the default style) and "Portrait Images" (which would use this styling; and if a person doesn't have an image it would use a gravatar or something).

In Slack there were thoughts that having an add-on of an add-on might get confusing, although I think you'll agree, the plugin I attached is mostly just a CSS snippet... (in fact, for starters, I may just dump the CSS into the EE code snippets library... but having this in the main add-on might still be good.)

## Bug report or feature request?

* [ ] Bug
* [x] Feature
* [ ] Neither

## Environment Data:

Version of EE core: 4.9.56

Version of this addon: 1.0.8.rc.003 

Version of WordPress: 4.9.6-RC1-43241

PHP Version:  7.1.4 

Browser used:  Mozzila Firefox

**Comment by sethshoultes** [comment]
@nerrad can you please merge in these CSS changes to the people addon?

**Comment by mnelson4** [comment]
FYI I don’t think these changes are ready as-is. They look better IMO if the people have profile images, but if they don’t, or if some do and some don’t, it looks worse. I’m not sure what to do about that...
My vote is for now it should just be a code snippet in the snippets library

**Comment by sethshoultes** [comment]
Okay. Thanks for the feedback Mike.

**Comment by mnelson4** [comment]
Ok here's a code snippet for it: https://github.com/eventespresso/ee-code-snippet-library/blob/master/addons/eea-people/mn_eea_people_list_thumbnail_styling.css
If there is more demand for this, we can bring this up again. For now I consider this done.
